### ISSUE TITLE
Incremental Status pulls from Haas hitting attribute conversion error

### ISSUE THREAD

**Issue by olsch01** [cbpowell/SenseLink#10]
Hi there, me again.  Getting to dig into this a little more today after the initial issue yesterday, and hitting a different snag than before.  Current issue is SenseLink properly pulling the initial power usage of each defined device, but subsequent updates are failing which causes SenseLink to start returning 0 instead of the current value.

Here's my current config:
`
sources:
- hass:
    url: "ws://127.0.0.1:8123/api/websocket"
    auth_token: "<REMOVED>"
    plugs:

        # Direct power usage reporting example
        - Dehumidifer:
            alias: "Dehumidifier"
            entity_id: switch.crawl_dehumidifier 
            power_keypath: "attributes/current_power_w"
            mac: 53:75:31:f6:4b:04
            off_state_value: "off"
            on_state_value: "on"
`

NOTE: Without specifying the off and on state values, I was getting a different "attribute" related error that causes devices to just stay at the initial read power usage indefinitely.

Here's what the Debug is kicking back:

`DEBUG:root:Entity update received: {'entity_id': 'switch.crawl_dehumidifier', 'state': 'on', 'attributes': {'current_power_w': 551.19, 'today_energy_kwh': 3.5851, 'voltage': 121.15, 'weekly_energy_total': 41.5754, 'monthly_energy_total': 8.7098, 'yearly_energy_total': 263.9509, 'friendly_name': 'Crawl Dehumidifier'}, 'last_changed': '2020-09-01T22:16:08.674118+00:00', 'last_updated': '2020-09-02T13:08:47.765819+00:00', 'context': {'id': '96a664b9741041dca6547d3f14b09974', 'parent_id': None, 'user_id': None}}
DEBUG:root:Entity Dehumidifer set to ON based on state_value
DEBUG:root:Pulling power from keypath: attributes/current_power_w for Dehumidifer
INFO:root:Updated wattage for Dehumidifer: 551.19

...

**DEBUG:root:Unable to convert attribute path attributes/current_power_w value (None) to float, using None**
DEBUG:root:Entity Dehumidifer set to ON based on state_value
INFO:root:Updated wattage for Dehumidifer: 0.0

`

So interestingly enough the initial grab of the current_power_w value works just fine, but subsequent updates are having trouble reading it.  Wanted to get this posted for documentation purposes before I took some time and started digging into the code a little in case this has come up previously.   Any thoughts appreciated!

**Comment by cbpowell** [comment]
I think I've maybe found the issue!

In the code that sorts out the appropriate "full" JSON keypath, it looks like I left off the `root_path` prefix. The `root_path` is either nothing for the bulk/initial update, or `"new_state"` for the incremental updates. So it makes sense (no pun intended) you get the initial but not the incremental updates.

If you want to try adjusting it manually, try changing this **line 161** in DataSource.py from the current:

https://github.com/cbpowell/SenseLink/blob/2decf3c47a6daff67accb3a9c7f21bb21bd544af/DataSource.py#L155-L161

To the following:
```python
# Get value at power keypath as attribute
attribute_path = root_path + self.power_keypath
```

**Comment by olsch01** [comment]
Bingo - It looks like that did the trick!  I was working backwards to that function with some debugging (I'm a terrible coder) and scratching my head how it had the right attribute_path, but the value was always returning "None".  Initial run appears to be working now - I'm going to lower the debug and let it bake for just a bit and will get you a more definitive update.  Thanks!

**Comment by cbpowell** [comment]
Sounds good - referenced it in a commit which I forgot auto-closes it…will leave it open for now until you are confident it's all working right.

**Comment by olsch01** [comment]
All good - it's been running solid for awhile now and keeping up with changes as I've tested out across state changes, usage changes, etc.  Simple fix - but all good now.  Thanks for pulling that out so quick!
