### ISSUE TITLE
SenseLink Responder stops working after invalid json received

### ISSUE THREAD

**Issue by olsch01** [cbpowell/SenseLink#11]
Ran into an issue a few times where the main process would continue to get updates as expected from Hass, but it would stop responding to the requests from Sense for status.  Found that this always happened after receiving the following in the debug log, which would only happen once every day or two:
2020-09-06 13:40:07,734 [MainThread  ] [DEBUG]  Did not receive valid json

Only way to fix this was to restart the process, and things would go back to normal until the next occurrence.

In SenseLink.py, line 228 does a "`Return True`" when this situation occurs and I believe that was causing the looping process to exit.  replaced with "`continue`", and it now still logs when there's an issue with the JSON is received, but then continues onto the next record and continues to function as expected.

**Comment by cbpowell** [comment]
Good catch, you're exactly right. With all the various testing, I don't think I've had my instance online long enough to hit that! Thanks again!
