### ISSUE TITLE
Error with Home Assistant 2023.5.0

### ISSUE THREAD

**Issue by asucrews** [cbpowell/SenseLink#21]
Hello,

I am not sure if this due to 2023.5.0 release or something else, however this logs repeats every 10 seconds. I am using docker to run senselink.

senselink  | INFO:root:Reconnecting in 10...
senselink  | INFO:root:Starting websocket client to URL: wss://<removed>/api/websocket
senselink  | DEBUG:root:Received message: {"type":"auth_required","ha_version":"2023.5.0"}
senselink  | INFO:root:Authentication requested
senselink  | DEBUG:root:Received message: {"type":"auth_ok","ha_version":"2023.5.0"}
senselink  | INFO:root:Authentication successful
senselink  | INFO:root:Event update request sent
senselink  | INFO:root:All states request sent
senselink  | DEBUG:root:Received message: {"id":1,"type":"result","success":true,"result":null}
senselink  | DEBUG:root:Potential event update received
senselink  | ERROR:root:Lost connection to websocket server (sent 1009 (message too big); no close frame received)

**Comment by cbpowell** [comment]
Well it may not be a problem with 2023.5.0 specifically, but do you have a sizable number of devices in Home Assistant?

While I haven't replicated it, this will seemingly happen when the WebSocket message is larger than [the default maximum of 1 MiB](https://websockets.readthedocs.io/en/stable/reference/asyncio/common.html#websockets.legacy.protocol.WebSocketCommonProtocol), and I'm guessing that might happen if HA has a ton of states to pass over (particularly on the first update).

This might be hard depending on how you've got SenseLink installed, but if you change [this line](https://github.com/cbpowell/SenseLink/blob/103147f7122391ec728078ab0a4acb78e929bdb2/senselink/homeassistant/ha_controller.py#L25) to: 
```python
async with websockets.connect(self.url, max_size=None) as websocket:
```
it should disable the maximum size limit. Not sure if that will cause problems or not…but I can work on adding it as a configuration parameter.

**Comment by cbpowell** [comment]
I added [release v2.1.0](https://github.com/cbpowell/SenseLink/releases/tag/2.1.0) but haven't had a chance to update any docs yet!

Hopefully this might fix it? To override the maximum message size, add the `max_message_size` value to the HASS configuration section:
```yaml
sources:
  - hass:
      url: "ws:///api/websocket"
      auth_token: "secret"
      max_message_size: "0"
      plugs:
         …
```

The default value is `1048576` bytes (2^20), but if you set it to `0` it should result in an unlimited size.

**Comment by cbpowell** [comment]
@asucrews Any luck with this change?

**Comment by asucrews** [comment]
Sorry for the late reply, I try this on Monday.  Work got in the way of
hobby time.

**Comment by cbpowell** [comment]
Going to close this one for now since it's working fine for me, but let me know if you're still having a problem!
