### ISSUE TITLE
Version 2.2.0 seems to use a function that will be deprecated, spamming log files.

### ISSUE THREAD

**Issue by mlebaugh** [cbpowell/SenseLink#23]
Updated to the latest and the logs are being spammed with the following:

WARNING:mqtt:filtered_messages() is deprecated and will be removed in a future version. Use messages() together with Topic.matches() instead.

No issues with this release, but this is filling up log files consistently.

**Comment by cbpowell** [comment]
Thanks for the heads up! I updated to use the new method of the aiomqtt library (plus I shouldn't have used such a loose dependency version requirement anyway).
