### ISSUE TITLE
Aggregate-type plugs

### ISSUE THREAD

**Issue by cbpowell** [cbpowell/SenseLink#5]
Add feature to define "aggregate" plugs that sum usage data from multiple individual plugs. Useful to observe the 20-plug Sense limit, or if you are interested in usage only at the level of all items of a type (e.g. all lights)

**Comment by pgenera** [comment]
You can do this with template sensors in HA that are then exposed, right?

Although I guess you could do that for the entity ratio plugs generally, so there must be a good reason for it.

**Comment by cbpowell** [comment]
Yeah true, with HA you could roll your own template to do that. Looking towards "broader" support such as when non-HA data source plugs are added, it might be more useful then.

**Comment by cbpowell** [comment]
Added in [Release 1.2.1](https://github.com/cbpowell/SenseLink/releases/tag/1.2.1).
