### ISSUE TITLE
HASS Direct Power with no key_path doesn't work

### ISSUE THREAD

**Issue by dlarrick** [cbpowell/SenseLink#6]
First of all, thanks for this project! This looks great! So great, in fact, that I'm playing around with it instead of packing for a (socially distanced) vacation.

I have a mini-split unit monitored by a Shelly EM power monitor that's integrated into HA. So its primary power value is in watts, and comes in on the entity's state, as described in the Wiki. But with a config like the following -- which I think should work -- 

```
sources:
  - hass:
      url: "ws://<server>:8123/api/websocket"
      auth_token: "<token>"
      plugs:
      - MiniSplits:
          alias: "Mini Splits"
          entity_id: sensor.mini_split_shelly
          mac: "<mac>"
          device_id: "<device_id>"
```

The first complaint I hit is "Attribute or attribute path not defined for plug MiniSplits". I hacked at it enough to get an initial reading and then fail to parse an update, but I am out of time for now. I also never did see a reading for this device in Sense (though the device does show up).

I am likely to debug this more myself when we return (in a week) and submit a patch, but I wanted to record the issue in case you (or someone else) would like to take a stab at it first.

FYI here are example initial and incremental update dicts from this entity:

Initial:
```
{
    'entity_id': 'sensor.mini_split_shelly',
    'state': '11',
    'attributes': {
	'shelly_type': 'Shelly EM',
	'shelly_id': '<omitted>',
	'ip_address': '192.168.1.114',
	'unit_of_measurement': 'W',
	'friendly_name': 'Mini Split Power',
	'icon': 'mdi:flash-outline'
    },
    'last_changed': '2020-08-15T13:31:56.235225+00:00',
    'last_updated': '2020-08-15T13:31:56.235225+00:00',
    'context': {
	'id': '4365142f43f942ed8510d71b04eee3ef',
	'parent_id': None,
	'user_id': None
    }
}
```

Incremental:

```
{
    'entity_id': 'sensor.mini_split_shelly',
    'old_state': {
	'entity_id': 'sensor.mini_split_shelly',
	'state': '11',
	'attributes': {
	    'shelly_type': 'Shelly EM',
	    'shelly_id': '<omitted>',
	    'ip_address': '192.168.1.114',
	    'unit_of_measurement': 'W',
	    'friendly_name': 'Mini Split Power',
	    'icon': 'mdi:flash-outline'
	},
	'last_changed': '2020-08-15T13:31:56.235225+00:00',
	'last_updated': '2020-08-15T13:31:56.235225+00:00',
	'context': {
	    'id': '4365142f43f942ed8510d71b04eee3ef',
	    'parent_id': None,
	    'user_id': None
	}
    },
    'new_state': {
	'entity_id': 'sensor.mini_split_shelly',
	'state': '13',
	'attributes': {
	    'shelly_type': 'Shelly EM',
	    'shelly_id': '<omitted>',
	    'ip_address': '192.168.1.114',
	    'unit_of_measurement': 'W',
	    'friendly_name': 'Mini Split Power',
	    'icon': 'mdi:flash-outline'
	},
	'last_changed': '2020-08-15T13:41:56.720476+00:00',
	'last_updated': '2020-08-15T13:41:56.720476+00:00',
	'context': {
	    'id': 'e2012a373d7d4490930b000ccddffac8',
	    'parent_id': None,
	    'user_id': None
	}
    }
}
```

**Comment by cbpowell** [comment]
Got it fixed I think - really appreciate the sample Websockets events too, super helpful to see what the output is for other devices.

I decided to stick with keeping it to the as-documented approach for now, so your original configuration listed above should now work. If no `power_keypath` or `attribute` keys are provided in the config, SenseLink will default to assuming the value provided by HASS for `state` is what it should use (with no scaling). I probably need to scan the wiki documentation again, to make sure that's what it actually says…

Enjoy the (wisely) socially-distanced vacation!
