### ISSUE TITLE
Support for HASS non-dimmer switches

### ISSUE THREAD

**Issue by dlarrick** [cbpowell/SenseLink#8]
Me again, back from vacation. I have a use case that I suspect is somewhat common that I can't figure out how to accomplish with the current code.

I have an on/off (non dimming) switch that is controlled by HASS. The load it controls is constant -- if the switch is off it's 0W; if it's on it's 19W. In my case it's a dumb Peltier-cooler-based dehumidifier, but I expect many loads (non-dimmable lights, resistance heaters, etc.) would be close enough to constant draw for this to be a reasonable approximation.

So I'd like to set up SenseLink to report either 0 or 19 watts depending on whether the load is off or on. But there's no 'brightness' or other numeric attribute to scale with.

Am I missing something? I could, of course, set up a template sensor to do the conversion inside HASS but it seems like this is a common enough scenario that you'd want to support it.

**Comment by cbpowell** [comment]
Welcome back! Nope you're not missing anything, currently the only way to set that up is with a HASS template like you mentioned - but I started to stub that out in the MQTT integration for just that reason.

Currently if you provide an `off_state_value` config and the `state` (or a `state_keypath` if provided) matches that off value, the off consumption (0W by default) is reported. So if we add an `on_state_value` config similar logic can be used.

My thinking is the pseudo code logic would be:
```python
if( state_value is something ) {
    if( state_value == on_state_value ) {
        power = max_watts
        # no return
        # This might get overwritten below if there's also an attribute defined
    }
    if( state_value == off_state_value ) {
        power = off_usage
        return
    }
}
if( attribute_value is something ) {
    # Continue evaluating and look for a NUMERIC attribute_value
    # …
    power = scaled_power
}

if( power is None ) {
    raise ValueError
}
self.power = power

**Comment by cbpowell** [comment]
Also I meant to ask - how does your device report on/off in the HASS WS API? Is it just "on" or "off" on the base `state` value? Can use this as an opportunity to get some sane default values (if "on"/"off" aren't them).

**Comment by dlarrick** [comment]
It's just in the base `state`, yeah, either 'on' or 'off'. This is a Z-Wave device. I suppose it could also be 'unavailable' if Z-Wave is broken or not up yet.

Sample:

```
{
  "entity_id": "switch.dryroom",
  "state": "on",
  "attributes": {
    "node_id": 2,
    "value_index": 0,
    "value_instance": 1,
    "value_id": "72057594076282880",
    "friendly_name": "Dryroom"
  },
  "last_changed": "2020-08-23T17:31:07.295994+00:00",
  "last_updated": "2020-08-23T17:31:07.295994+00:00",
  "context": {
    "id": "6d64a6e2e56611eaba70397c8f801102",
    "parent_id": null,
    "user_id": null
  }
}
```

**Comment by cbpowell** [comment]
I think this is now working in the `hass_state` branch I just pushed. Works for me on a test setup, want to give it a try?

**Comment by dlarrick** [comment]
Cool, I'll give this a try later this evening or tomorrow.

**Comment by dlarrick** [comment]
This seems to be working. My dryrooom setup is working with HASS templates so I did not mess with it, but I added:
```
      -	Patio:
          alias: "Patio"
          entity_id: switch.patio_wall
          mac: "53:75:31:A0:77:77"
          device_id: "1723aabb431c127e0648df16266c0209a5a07777"
          off_state_value: "off"
          on_state_value: "on"
          off_usage: 0
          max_watts: 60
```
(patio_wall is misnamed; it's actually controlling some string lights)
This definitely shows up in Sense when on, disappears when off. So that's good.

Two notes:
1. I am seeing:
```
ERROR:root:Unable to convert attribute path new_state/state value (off) to float, using None
ERROR:root:Unable to convert attribute path new_state/state value (on) to float, using None
```
But these messages do not seem to be consequential.

2. I'm specifying 60 watts as the max_watts, and SenseLink is sending:
```
INFO:root:Updated wattage for Patio: 60
```
But Sense is showing this device as consuming 62 watts. My other two emulated devices are also slightly high in Sense: 20W vs. 19 for the dehumidifier, 31 vs. 30 / 524 vs. 541 for my mini-split unit.  Not sure what's up with that.

**Comment by cbpowell** [comment]
Yeah I think the logged error is something I inadvertently left in - it tries to convert the status value to a float, but that obviously fails in this case because it’s the word “on”. That’s OK though, because as a result it doesn’t then overwrite the initial “on” value set to `max_watts`. I think I just need to downgrade that from an error to info/debug.

Good catch on the reported wattage difference! The only thing I can think of there is that Sense might apply an internal calibration to HS110 data? Like maybe in their testing the units always showed an consistent error, so they adjust for it.

We should be able to figure out calibration curve using the static-type plugs. Based on your initial points, seems like it corrects the value up somewhat-linearly, by a factor of `1.03`.

**Comment by dlarrick** [comment]
Sense seems to apply a correction factor to my real HS-110s as well. Their engineers must have discovered systemic inaccuracy -- or they have a bug.

**Comment by cbpowell** [comment]
Interesting - I guess I need to grab a Kill-a-Watt and get some accurate numbers. For both this and ESPSense, to calibrate those cheaper plugs.

Did you compare the reported numbers in the Kasa app vs. the Sense value to confirm the correction? One of my real HS110s is in front of my network components and reads 35.8W in Kasa, 36W in Sense. The 103% factor guesstimate would put that at ~36.9W, which I would have assumed Sense would round up to 37W for the integer-accuracy it presents to users.

I didn’t get a chance to play with static plugs yesterday to dial in the factor, planning to do that tonight.

**Comment by cbpowell** [comment]
So I just tried manually setting from 10W to 150W with a static-type plug, and I'm getting dead-on numbers reported by the Sense app…so now I don't know what's going on!

To troubleshoot:
1. Do you have Solar CTs? (I don't)
2. What does the SenseLink debug output have for the `Sending response` JSON? Does that number match what you put in the static config? (No idea how that could be different, but still)
3. What firmware version is reported for your Sense monitor in the app? (As of this writing, mine is 1.28.2819)

**Comment by dlarrick** [comment]
I do have solar CTs.

I will run the same experiment. I likely will not get a chance before the weekend but I'll report back.

My Sense monitor's software version is 1.28.2819 as well. It's a fairly early (2016) monitor so there may be something different going on there.

**Comment by cbpowell** [comment]
Main topic (non-dimmer switches) is incorporated, so I'll close the issue but we should continue to discuss the delta you're seeing!

**Comment by dlarrick** [comment]
Thanks.

It's definitely a scaling factor that Sense is applying to my real HS-110s as well. So far when I've investigated it's been during the day (so solar production occurring); I need to check again some evening.

That said, it's nothing your code is doing wrong so I'm not sure it makes sense (no pun intended) to track it here.

**Comment by cbpowell** [comment]
I wonder if it’s intentional? I mean having solar production doesn’t offset per-device consumption, or at least (at first glance) it seems like an odd way to bookkeep it.

**Comment by dlarrick** [comment]
The only way this makes sense: there's a longstanding hardware bug with the monitor where solar production reduces the reading from the main CTs. If they're fixing this with a global correction factor, it's possible it's getting applied to the smart plugs too (which would be a bug).
