### ISSUE TITLE
Issue Mapping Power Key

### ISSUE THREAD

**Issue by olsch01** [cbpowell/SenseLink#9]
Hi there, trying to configure SenseLink to map power usage from some eTekcity plugs that integrate with Homeassistant via the VEsync integration.

for one of the 3 targeted devices, the API returns:
{"attributes": {"current_power_w": 551.21, "friendly_name": "Crawl Dehumidifier", "monthly_energy_total": 3.772, "today_energy_kwh": 248.6639, "voltage": 123.74, "weekly_energy_total": 42.8791, "yearly_energy_total": 259.0131}, "context": {"id": "59e4aa5790284f64866da965d0aceaf1", "parent_id": null, "user_id": null}, "entity_id": "switch.crawl_dehumidifier", "last_changed": "2020-09-01T18:45:57.907076+00:00", "last_updated": "2020-09-01T19:56:14.656995+00:00", "state": "on"}

While in the examples provided I see you can nest power_keypath value in cases where the value is buried.  In this case, the targeted value I'm trying to get is "attributes/current_power_w", however, the mapping does not seem to be working as I'd expect.

Here's my snippet from config.yml
        # Direct power usage reporting example
        - Dehumidifer:
            alias: "Dehumidifier"
            entity_id: switch.crawl_dehumidifier
            power_keypath: "attributes/current_power_w"
            mac: 53:75:31:f6:4b:04
            max_watts: 900

SenseLink Debug output:
DEBUG:root:Sending response: {'emeter': {'get_realtime': {'current': 0.0, 'voltage': 120, 'power': 0.0, 'total': 0, 'err_code': 0}}, 'system': {'get_sysinfo': {'err_code': 0, 'sw_ver': '1.2.5 Build 171206 Rel.085954', 'hw_ver': '1.0', 'type': 'IOT.SMARTPLUGSWITCH', 'model': 'SenseLink', 'mac': '53:75:31:F6:4B:04', 'deviceId': 'E55830B46365D700D80CFD82F0D85EF3BCD3F40D', 'alias': 'Dehumidifier', 'relay_state': 1, 'on_time': 133.28122234344482}}}

Anything obvious I'm missing here, or is the issue that this value is buried under "attributes" whereas it seems most other situations have the value buried somewhere under "state"

Appreciate it!

**Comment by cbpowell** [comment]
Thanks for posting a new scenario! You’re definitely on the leading edge of testing, so I appreciate the feedback.

That should still work (in theory) to specify a power value inside the attributes, because SenseLink should just follow the keypath through the JSON starting from the root, and if it finds a numeric value, it’ll use it. 

I can’t currently take a look in detail but will look more closely this evening. In the interim, are there any other debug log entries from just before the response? Or alternatively right at launch, where it describes some of the setup for that plug?

Side note - you shouldn’t need to define `max_watts` for a direct power usage, but I realize it probably says that’s “required” in the docs currently. Will have to change that.

**Comment by olsch01** [comment]
Appreciate the quick follow-up and details!  I did add in the max_watts because I believe it said required, but I'll remove that going forward as we test this out.

Here's the first several lines from the Debug output - note that the HAAS instance is local so the localhost reference for the API call is accurate.  Though now that I look further, I do see intermediate errors connecting to the API, even though hitting it via curl returns valid responses.

-----
DEBUG:root:Using config at: ./config.yml
INFO:root:Will respond to Sense broadcasts
INFO:root:Starting SenseLink controller
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:root:Configuration loaded: {'sources': [{'hass': {'url': 'ws://127.0.0.1:8123', 'auth_token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjYmY5MGFmMzFhOWU0MTYxOWZlMDZlZDA5NzYyOTkxMyIsImlhdCI6MTU5ODk4NjQ3MywiZXhwIjoxOTE0MzQ2NDczfQ.f-TkFNZzNT98iNGL93XG0oSEPd11wVM46S4cG_j08Mg', 'plugs': [{'FrontLandscape': {'alias': 'Front Landscape Lights', 'entity_id': 'switch.front_landscape', 'power_keypath': 'attributes/current_power_w', 'mac': '53:75:31:f6:4b:02', 'max_watts': 150}}, {'BackLandscape': {'alias': 'Back Landscape Lights', 'entity_id': 'switch.backyard', 'power_keypath': 'attributes/current_power_w', 'mac': '53:75:31:f6:4b:03', 'max_watts': 150}}, {'Dehumidifer': {'alias': 'Dehumidifier', 'entity_id': 'switch.crawl_dehumidifier', 'power_keypath': 'attributes/current_power_w', 'mac': '53:75:31:f6:4b:04', 'max_watts': 900}}]}}]}
DEBUG:root:Adding hass configuration
INFO:root:Generating HASS instances
INFO:root:Spoofed Device ID: 8fff37cfedfd90b1e46d59490f8fbaab7d778eeb
DEBUG:root:Added plug: FrontLandscape
INFO:root:Spoofed Device ID: d84c419c215183e2ee43aa9ee29fd923b9715390
DEBUG:root:Added plug: BackLandscape
INFO:root:Spoofed Device ID: e55830b46365d700d80cfd82f0d85ef3bcd3f40d
DEBUG:root:Added plug: Dehumidifer
INFO:root:Starting UDP server
INFO:root:Starting websocket client to URL: ws://127.0.0.1:8123
ERROR:root:Unable to connect to server at ws://127.0.0.1:8123 (<class 'websockets.exceptions.InvalidStatusCode'>:server rejected WebSocket connection: HTTP 200)
INFO:root:Attempting to reconnect in 10...
DEBUG:root:Broadcast received from: 192.168.2.162: {'emeter': {'get_realtime': {}}, 'system': {'get_sysinfo': {}}}
DEBUG:root:Sending response: {'emeter': {'get_realtime': {'current': 0.0, 'voltage': 120, 'power': 0.0, 'total': 0, 'err_code': 0}}, 'system': {'get_sysinfo': {'err_code': 0, 'sw_ver': '1.2.5 Build 171206 Rel.085954', 'hw_ver': '1.0', 'type': 'IOT.SMARTPLUGSWITCH', 'model': 'SenseLink', 'mac': '53:75:31:F6:4B:02', 'deviceId': '8FFF37CFEDFD90B1E46D59490F8FBAAB7D778EEB', 'alias': 'Front Landscape Lights', 'relay_state': 1, 'on_time': 1.2765779495239258}}}
DEBUG:root:Sending response: {'emeter': {'get_realtime': {'current': 0.0, 'voltage': 120, 'power': 0.0, 'total': 0, 'err_code': 0}}, 'system': {'get_sysinfo': {'err_code': 0, 'sw_ver': '1.2.5 Build 171206 Rel.085954', 'hw_ver': '1.0', 'type': 'IOT.SMARTPLUGSWITCH', 'model': 'SenseLink', 'mac': '53:75:31:F6:4B:03', 'deviceId': 'D84C419C215183E2EE43AA9EE29FD923B9715390', 'alias': 'Back Landscape Lights', 'relay_state': 1, 'on_time': 1.2788360118865967}}}
DEBUG:root:Sending response: {'emeter': {'get_realtime': {'current': 0.0, 'voltage': 120, 'power': 0.0, 'total': 0, 'err_code': 0}}, 'system': {'get_sysinfo': {'err_code': 0, 'sw_ver': '1.2.5 Build 171206 Rel.085954', 'hw_ver': '1.0', 'type': 'IOT.SMARTPLUGSWITCH', 'model': 'SenseLink', 'mac': '53:75:31:F6:4B:04', 'deviceId': 'E55830B46365D700D80CFD82F0D85EF3BCD3F40D', 'alias': 'Dehumidifier', 'relay_state': 1, 'on_time': 1.2806427478790283}}}
DEBUG:root:Broadcast received from: 192.168.2.162: {'emeter': {'get_realtime': {}}, 'system': {'get_sysinfo': {}}}
DEBUG:root:Sending response: {'emeter': {'get_realtime': {'current': 0.0, 'voltage': 120, 'power': 0.0, 'total': 0, 'err_code': 0}}, 'system': {'get_sysinfo': {'err_code': 0, 'sw_ver': '1.2.5 Build 171206 Rel.085954', 'hw_ver': '1.0', 'type': 'IOT.SMARTPLUGSWITCH', 'model': 'SenseLink', 'mac': '53:75:31:F6:4B:02', 'deviceId': '8FFF37CFEDFD90B1E46D59490F8FBAAB7D778EEB', 'alias': 'Front Landscape Lights', 'relay_state': 1, 'on_time': 1.4782207012176514}}}
DEBUG:root:Sending response: {'emeter': {'get_realtime': {'current': 0.0, 'voltage': 120, 'power': 0.0, 'total': 0, 'err_code': 0}}, 'system': {'get_sysinfo': {'err_code': 0, 'sw_ver': '1.2.5 Build 171206 Rel.085954', 'hw_ver': '1.0', 'type': 'IOT.SMARTPLUGSWITCH', 'model': 'SenseLink', 'mac': '53:75:31:F6:4B:03', 'deviceId': 'D84C419C215183E2EE43AA9EE29FD923B9715390', 'alias': 'Back Landscape Lights', 'relay_state': 1, 'on_time': 1.4800834655761719}}}
DEBUG:root:Sending response: {'emeter': {'get_realtime': {'current': 0.0, 'voltage': 120, 'power': 0.0, 'total': 0, 'err_code': 0}}, 'system': {'get_sysinfo': {'err_code': 0, 'sw_ver': '1.2.5 Build 171206 Rel.085954', 'hw_ver': '1.0', 'type': 'IOT.SMARTPLUGSWITCH', 'model': 'SenseLink', 'mac': '53:75:31:F6:4B:04', 'deviceId': 'E55830B46365D700D80CFD82F0D85EF3BCD3F40D', 'alias': 'Dehumidifier', 'relay_state': 1, 'on_time': 1.4822275638580322}}}
DEBUG:root:Broadcast received from: 192.168.2.162: {'emeter': {'get_realtime': {}}, 'system': {'get_sysinfo': {}}}
DEBUG:root:Sending response: {'emeter': {'get_realtime': {'current': 0.0, 'voltage': 120, 'power': 0.0, 'total': 0, 'err_code': 0}}, 'system': {'get_sysinfo': {'err_code': 0, 'sw_ver': '1.2.5 Build 171206 Rel.085954', 'hw_ver': '1.0', 'type': 'IOT.SMARTPLUGSWITCH', 'model': 'SenseLink', 'mac': '53:75:31:F6:4B:02', 'deviceId': '8FFF37CFEDFD90B1E46D59490F8FBAAB7D778EEB', 'alias': 'Front Landscape Lights', 'relay_state': 1, 'on_time': 3.2596724033355713}}}
DEBUG:root:Sending response: {'emeter': {'get_realtime': {'current': 0.0, 'voltage': 120, 'power': 0.0, 'total': 0, 'err_code': 0}}, 'system': {'get_sysinfo': {'err_code': 0, 'sw_ver': '1.2.5 Build 171206 Rel.085954', 'hw_ver': '1.0', 'type': 'IOT.SMARTPLUGSWITCH', 'model': 'SenseLink', 'mac': '53:75:31:F6:4B:03', 'deviceId': 'D84C419C215183E2EE43AA9EE29FD923B9715390', 'alias': 'Back Landscape Lights', 'relay_state': 1, 'on_time': 3.260676622390747}}}
DEBUG:root:Sending response: {'emeter': {'get_realtime': {'current': 0.0, 'voltage': 120, 'power': 0.0, 'total': 0, 'err_code': 0}}, 'system': {'get_sysinfo': {'err_code': 0, 'sw_ver': '1.2.5 Build 171206 Rel.085954', 'hw_ver': '1.0', 'type': 'IOT.SMARTPLUGSWITCH', 'model': 'SenseLink', 'mac': '53:75:31:F6:4B:04', 'deviceId': 'E55830B46365D700D80CFD82F0D85EF3BCD3F40D', 'alias': 'Dehumidifier', 'relay_state': 1, 'on_time': 3.261765956878662}}}

----

**Comment by olsch01** [comment]
Disregard - turns out I didn't properly reference the Websockets URL with the "/api/websocket" appended to the haas url.  Missed that detail.

Looks like it is in fact grabbing the proper value under attributes as mapped - will continue to play around with this a little.  Really appreciate you building this out - super helpful for cases where we have energy monitoring capable plugs that Sense doesn't support!

**Comment by cbpowell** [comment]
Just noticed that myself too! However that's an important detail missing from the docs as well, so I'll make that change on the HASS wiki page now.

And glad to help and see SenseLink being used!
